### ISSUE TITLE
Attempted build in Qt 5.11.2 gives error C2664

### ISSUE THREAD

**Issue by TombstoneTumbleweedArt** [Jim-Eckerlein/VoxelFractalGenerator#3]
Generator.cpp:11: error: C2664: 'void jim::voxelfractalgenerator::VoxReader::load(std::istream &,jim::voxelfractalgenerator::Model &)': cannot convert argument 1 from 'std::ifstream' to 'std::istream &'

Not sure why this occurs.  No changes made from main branch, just unpacked the zip and attempted build.

**Comment by Jim-Eckerlein** [comment]
I'll check it out.

**Comment by Jim-Eckerlein** [comment]
So, I've fixed the error. (One had to use a local instead of a temporary for a stream argument. For some reason, this worked 2 years ago...)
Unfortunately, the program keeps crashing and not only in the latest commit.
Because this is a very old project of mine and I haven't worked on it for 2 years, I won't examine the issue further and mark the repository as archived.
